_target_: src.smart.model.smart_gail.SMART_IQ

defaults:
  - smart

model_config:
  n_batch_wosac_metric: 2
  n_vis_batch: 0
  n_vis_scenario: 40
  n_vis_rollout: 32
  decoder:
    num_map_layers: 1
    num_agent_layers: 1
    pl2pl_radius: 20
    pl2a_radius: 40
    dropout: 0 #0.1
    hist_drop_prob: 0 #0.1
    pt2pt_neighbor: 30
    pt2a_neighbor: 20
    a2a_neighbor: 20