_target_: src.smart.model.smart_gail.SMART_GAIL

defaults:
  - smart

model_config:
  val_open_loop: False
  token_processor:
    pred_init: False
    learn_init: False
    learn_autoencoder: False
  n_batch_wosac_metric: 1
  n_vis_batch: 0
  n_vis_scenario: 40
  n_vis_rollout: 32
  decoder:
    num_map_layers: 1
    num_agent_layers: 3
    pl2pl_radius: 20
    pl2a_radius: 40
    dropout: 0 #0.1
    hist_drop_prob: 0 #0.1 #0.1
    pt2pt_neighbor: 30
    pt2a_neighbor: 20
    a2a_neighbor: 20
    time_span: 60

    dis_a2a_radius: 0

    dis_weight: 20
    dist_decay: 3
    reward_weight: 0
    reward_decay: 2.5



