_target_: src.smart.model.smart_gail.SMART_IQ

defaults:
  - smart

model_config:
  n_batch_wosac_metric: 2
  n_vis_batch: 0
  n_vis_rollout: 1
  decoder:
    num_map_layers: 1
    num_agent_layers: 1