# https://wandb.ai
#
#wandb:
# _target_: lightning.pytorch.loggers.wandb.WandbLogger
# name: ${task_name}
# save_dir: "${paths.output_dir}"
# offline: False
# id: null # pass correct id to resume experiment!
# anonymous: null # enable anonymous logging
# project: bc
# log_model: False # upload lightning ckpts
# prefix: "" # a string to put at the beginning of metric keys
# entity: u3006612
# group: ""
# tags: []
# job_type: ""
# resume: allow

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: ${task_name}
  save_dir: ${paths.output_dir}
  project: bc
  entity: u3006612
  log_model: false
  offline: true   # This already tells WandbLogger to run offline
  id: null
  resume: "never"
  group: ""
  tags: []
  job_type: ""
  prefix: ""

  # extra kwargs go directly to wandb.init()
  init_kwargs:
    settings:
      start_method: "thread"   # safer with multiprocessing
      # mode: "offline"        # not needed if offline: true


# tensorboard:
#   _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
#   save_dir: ./logs  # Set your desired logging directory
#   name: ${task_name} # Experiment name
#   version: ${paths.output_dir}  # Auto-increments the version