defaults:
  - model_checkpoint
  - model_summary
  - learning_rate_monitor
  - _self_
#
#model_checkpoint:
#  dirpath: ${paths.output_dir}/checkpoints
#  filename: "epoch_{epoch:03d}"
#  save_last: link
#  auto_insert_metric_name: false
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: null
  filename: "epoch={epoch}-step={step}-val_closed_wosac={val_open/acc:.4f}"
  monitor: "val_open/acc"
  verbose: false
  save_last: true
  save_top_k: 64
  mode: "max"
  auto_insert_metric_name: false
  save_weights_only: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: false

model_summary:
  max_depth: -1
