# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: null     # or any directory you prefer
    filename: "epoch={epoch}-valmeta={val_closed/wosac_likelihood/metametric:.4f}"
    monitor: "val_closed/wosac_likelihood/metametric"   # <== key metric from validation
    verbose: false
    save_last: true
    save_top_k: 3
    mode: "max"                          # "max" since your metric increases with performance
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: false       # <== important, disables save after training epoch