# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: waymo
  - model: smart
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: iq #iq #ego_gmm_pre_bc  #wosac_sub #iq #iq

action: fit # fit, finetune, validate, test

# task name, determines output directory path
task_name: x2_2_relpos_meantype_valid_nearestlane20max #_r30 #_nomask #_inter2pt_inter4 #_lanemean #_val256 #_entropy001 #_entropy01 #_drop01bc__noptdetach #_done #rkl_copy1e3_ScurrentV10_targetV #_decay0 # ratio002 #10 #     #_soft1e4_timespan5 #000_gamma0_roll10_len100 #BC_1exp1Vclip  #2SVclip #1exp2V #_drop0_rollout1_maxlen1 #Q01_01BC_mymatchx2_1e2_soft0005_32_min1e4rkl1_clip

# simply provide checkpoint path to resume training
ckpt_path: null
train_log_dir: null

# seed for random number generators in pytorch, numpy and python.random
seed: 817
