# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: waymo
  - model: smart
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: iq #_val #iq #ego_gmm_pre_bc  #wosac_sub #iq #iq

action: fit # fit, finetune, validate, test

# task name, determines output directory path
task_name: awbc64_baseline2_highest #gaussian1e4 #medium #expertnoise1e3_advexpert #_traivalue99 #sa #_return09 #_beta05 ##_cache #return05_beta2 #_train_cache #return03 #_amap1 #_return05_nolight #_l12 #_return_detach #_light12nogailreturn #advwbc #095 #lightmap #pt20_layer13    #nohigh_advwbc #return #high #high_Bce_h800 #4090 #h800 #4090 #h800 #4090 #h800 #4090 #h800 #4090 #h800 # #h800est #estmedium #16_disa2a #ptr30_20 #_dis_detach #layer112  #_targetiq #_layer12 #iqbc #iq_allmykdist    #03_diff_last  #       #@01_rollvalid_nodetach #_nodetach #diff #residx_nodetach #_pkil #nonoise05 #_map4 #_maptoken #_sa #_nonoise_difflast #_8192_iq #lightformer_nonoise_notoken #nores #_shuffle_shuffle_noraw #tokensame #_detach_raw_iq #_res_real_dist05_iq #4096_all_center4096_iq #_center01_iq #_detach_raw_centerinter_post #dyanmic #8192_iq #5Hz_iq997 #embed_5Hz_iq1 #dynamicpost51      #_5hz_start_nolight_trainmask #_expertinit1_post0222 #_recoil #_local #target  #gaussianpos3Mapadd1_d5 #_iqLearn05 #_rollpost_noexpertnll_tpred

# simply provide checkpoint path to resume training
ckpt_path: null
train_log_dir: null

# seed for random number generators in pytorch, numpy and python.random
seed: 817

cfg: null
