# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: waymo
  - model: smart
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: iq #iq #ego_gmm_pre_bc  #wosac_sub #iq #iq

action: fit # fit, finetune, validate, test

# task name, determines output directory path
task_name: bc32_pt30_share_mix05x2_freq5_len50 #qatten     #_trainmask_rangea2aflip #_05mixx2 #_rewa #_batchmean_map #_map_expert_mixrkl_gnn_nofilter_share

# simply provide checkpoint path to resume training
ckpt_path: null
train_log_dir: null

# seed for random number generators in pytorch, numpy and python.random
seed: 817
