# Data Configuration
data:
  template_path: "data/data_template.pth"

# Image Configuration
image:
  size: 200
  target_size: [560, 315]


data_path: "./waymo/desay_map" #"./waymo/desay_map"

planner_path: "/home/ke/code/catk/src/waymo_data/epoch=2-step=20000.ckpt"#"/home/ke/code/catk/src/waymo_data/ckpts/epoch=21-step=223212.ckpt"

camera_parameter_path: "./waymo/sensor_json/calibrated_sensors.json"

output_json_path: "./waymo/json_output/labels_occluded.json"

input_json_path: #"./waymo/json_input/static_ego.json"  #edit ego (or other) agent behavior like static_ego.json

gui_display: True

gui_show_static_id: False

lidar_height: 1.84

export_mode: "all" #    -> 仅导出交通参与者 ,"all"          -> 导出交通参与者 + 静态障碍物 + 交通灯

max_sim_time: 90 #9s

random_seed: 3

agent_density: 0.5 #0 : no agent , 1: max number agent

agent_class_ratio:
  pedestrian: 1
  car: 8
  truck: 2
  bicycle: 1

agent_size:
  pedestrian: [0.8, 0.8, 1.7]
  bicycle: [1.8, 0.8, 1.7]
  car: [4.8, 2, 1.7]
  truck: [8.0, 2.5, 3.6]
  ego: [4.8, 2, 1.7]

static_density: 0.5 #0 : no agent , 1: max number agent

static_class_ratio:
  cone: 1
  water_barrier: 2
  hydrant: 1

static_size:
  cone: [0.5, 0.5, 1]
  water_barrier: [4, 0.5, 1]
  hydrant: [0.5, 0.5, 1]

static_object:
  add: #static object
#    - type: 'hydrant'  #cone,water_barrier,hydrant
#      id: -1
#      position: [0,0]
#      heading:  1.57
#      shape : #可选, 可根据type生成
  remove:
#    - id: -2 # give the remove agent id


map_object:
  add: #static object
#    - class: lane_line #[lane_line,boundary,speed_bump,crosswalk]
#      attrs:
#        laneline_type: solid #[solid, dot]
#      xyz:
#        - [0 , 0] #x
#        - [0, 500] #y
#        - [0 , 0] #z
#      global_id: -100
  remove:
#    - id: 35

agent:
  add:
#    - type: 'car'  #pedestrian,bicycle,car,truck
#      id: 0
#      position: [5, -20]
#      goal: # [5,200]   # 可选
#      heading:   1.57    # 可选, 可根据goal生成
#      speed:  #可选, 可根据type生成
#      shape: #可选, 可根据type生成
  remove:
  stop:


traffic_lights:
  - position:  [20, 200]    # 信号灯的世界坐标
    heading: 0
    size: [1,1,5]
    orientation: "vertical"         # vertical | horizontal
    type:                           # 灯泡组合类型 #color: red, yellow, green # shape: circle, left_arrow,right_arrow,forward_arrow,uturn
      - color: "red"
        shape: "left_arrow"
      - color: "yellow"
        shape: "circle"
      - color: "green"
        shape: "circle"
    mode: "periodic"                # fixed | periodic | custom
    periodic_schedule:              # 周期性切换设置
      cycle_time: 60.0              # 整个周期长度（秒）
      phases:                       # 每个状态阶段
        - duration: 2.0
          lights_on:
            - color: "green"
        - duration: 5.0
          lights_on:
            - color: "yellow"
        - duration: 25.0
          lights_on:
            - color: "red"
