# Data Configuration
data:
  template_path: "data/data_template.pth"

# Image Configuration
image:
  size: 200
  target_size: [560, 315]


data_path: "./waymo/desay_map" #"./waymo/desay_map"

planner_path: "./waymo/model_checkpoint/sim.ckpt"

camera_parameter_path: "./waymo/sensor_json/calibrated_sensors.json"

output_json_path: "./waymo/json_output/labels_occluded.json"

input_json_path: #"./waymo/json_input/static_ego.json"  #edit ego (or other) agent behavior like static_ego.json

gui_display: False

lidar_height: 1.84

max_sim_time: 500 #300 #9s

random_seed: 42

static_object:
  add:

map_object:
  add:
  remove:

agent:
  add:
  remove:
  stop:
  recording:

traffic_lights:

